language: c
before_install:
- sudo apt-get -qq update
- sudo apt-get install -y git debhelper fakeroot
- sudo apt-get install -y libpcap-dev libselinux1-dev
- sudo apt-get install -y binutils-mingw-w64-i686 gcc-mingw-w64 mingw-w64-i686-dev
  mingw-w64-common
- sudo apt-get install -y autoconf automake dh-autoreconf
after_failure:
- cat config.log
script:
- ./autogen.sh
- git clean -df . && dpkg-buildpackage -b -us -uc
- git clean -df . && export CC=i686-w64-mingw32-gcc && ./autogen.sh --host=i686-w64-mingw32
  --build=$(gcc -dumpmachine)
env:
  global:
    secure: G3qiIHVbyvND++kUY/bEED+qIfve8I/6CV6VSYvQhIjaSVtG42XcdT/AgoYyS9kS5rqkYPSQyYSIYVCqYGAH1GWy0P1/qQHrLawVAOZVwLmWbUX8jBS/cnlJ9TLniy4pTD59+0nE19GUSm6EoJSEDtUQcDjZyr95nZwNwOPzohOgw0B0CprbJQpg1NGKw1YrZ+RfKBsmhEwT0EFRg9Q3UWBnXPHVyri4LnJ53D+FkTkA+MLOKxaAK50vhGaGy5oRUW5Uf95vFZw3FhXqJbiR2FbMLXP5gxS4swnduBsbycwV/RYbR4M/MtRt51JqpcOgXPRnyVEPKzbpuqqFQFAXt7ZRur0G3Lr7iVJ2Yc8/TFkFwaIMLMBE1UAyhgi8QBEJhdgXKp5a4B9Qouebnpp3w4znUrd037ZaVdfSruqqBl1QTYPYcUAYrKbPZIxGTQGJGHJbQw48sl4r/ssZj9NKnijfgZW3jxNJnvUPTuEFGnsdFqEwv5HxO4O3UWp5vrwX1sC+1+QrAsE+3fUmX4x1J39XOU9u0cAcBtnj88t9uRYndB3OhXqAp2hHNy7YQlDsnaNTvqIVt3W7na5HwjlZ320aFTRSdC/j/rd8O5CEgaCJK4GP2Gwcvffom4yOGt9+gO2aYSOosfkkjT5G6cdYOUr+fKR0ZUQ2uaw2njatswQ=
addons:
  coverity_scan:
    project:
      name: lnslbrty/ptunnel-ng
    notification_email: matzeton@googlemail.com
    build_command_prepend: autoreconf -i && ./configure
    build_command: make
    branch_pattern: coverity_scan
